<?xml version="1.0"?>
<!DOCTYPE person [
    <!ELEMENT first_name (#PCDATA)>
    <!ELEMENT last_name ( #PCDATA )>
    <!ELEMENT profession (#PCDATA)>
    <!ELEMENT name (first_name|last_name)>
    <!ELEMENT person (name, profession*)>
    <!ATTLIST image source  CDATA #REQUIRED
                    width   CDATA #REQUIRED
                    height  CDATA #REQUIRED
                    alt     CDATA #IMPLIED
    >
]>
<person>
    <name>
        <first_name>Alan</first_name>
    </name>
    <image source="source_value" width="width_value" height="heigth_value"/>
    <profession>computer scientist</profession>
    <profession>mathematician</profession>
    <profession>cryptographer</profession>
</person>
